### ISSUE TITLE
Inflatable Airbags placed in symmetry do not inflate when put in action group

### ISSUE THREAD

**Issue by Grunf911** [BobPalmer/SrvPack#26]
I have added Inflatable Airbags placed in VAB in MM symmetry to custom group 5, (when putting on my rover - controlled by small probe probodyne okto2 through remotetech). I tried inflating them on the landing pad but only the one i placed inflated

the mirrored one did not inflate, and when tried to manually inflate through right click, I had the option to inflate, but no animation, or inflation happened

**Comment by BobPalmer** [comment]
Closing as this is likely related to the recharge mechanic and that is being deprecated next release
