### ISSUE TITLE
Kerbal duplicates on boarding (rescue mission)

### ISSUE THREAD

**Issue by akasurak** [BobPalmer/SrvPack#32]
I get an error message trying to board a freshly rescued kerbal (v1.0.2) saying a newly inflated module is full. On switching back to the craft, it indeed already contains the kerbal who is still very visible on the ladder. If I EVA that kerbal, the original, ladder bound rescuee is thrown off into space. Trying to board another lifeboat on the same craft gives the same error, but does not result in a third kerbal.

Many other mods installed. Linux x64. Everything uptodate via steam and ckan.

**Comment by BobPalmer** [comment]
Gender of the Kerbal in question?  Do you have KIS installed?

**Comment by akasurak** [comment]
piloted by val, rescuing a male. Not sure what KIS is, so probably not.

Furthermore, if I hyperedit the craft back to kerbin, the mission doesn't complete, and val goes MIA.

modlist: http://pastebin.com/ZBMvdyYm

**Comment by BobPalmer** [comment]
Closing, unable to repro, sounds like a stock bug
