### ISSUE TITLE
Version URL in SrvPack.version is incorrect

### ISSUE THREAD

**Issue by timmersuk** [BobPalmer/SrvPack#45]
In the current release, in SrvPack.version, the URL is incorrect resulting in AVC not picking up on new version releases.

https://raw.githubusercontent.com/BobPalmer/SrvPack/master/GameData/UmbraSpaceIndustries/SrvPack/SrvPack.version

I'm not sure, but I think this should probably be updated to :

https://raw.githubusercontent.com/BobPalmer/SrvPack/master/FOR_RELEASE/GameData/UmbraSpaceIndustries/SrvPack/SrvPack.version

**Comment by BobPalmer** [comment]
Fixed
