### ISSUE TITLE
DERP solar panels power gen does not match texture

### ISSUE THREAD

**Issue by bobprime** [BobPalmer/SrvPack#50]
The panels that come with the derp pack look like they are solar collection arrays on both sides, but only one side (the down facing side when the part is put on a vertical rocket) generates power.  See screenshots where both sides are shown face on to the sun but only one side generates power.

It might be cheesy to use the parts on a probe but they make such great micro descender parts.

![screenshot12](https://cloud.githubusercontent.com/assets/50050/11012906/f69be214-84c9-11e5-8272-2c92a402e391.png)
![screenshot13](https://cloud.githubusercontent.com/assets/50050/11012908/faae0e36-84c9-11e5-92ac-6a26acf9fa8d.png)

**Comment by BobPalmer** [comment]
Switched to a spherical model so these can act as double sided
