### ISSUE TITLE
Deploying Legs w/7.2 of Firespitter not available

### ISSUE THREAD

**Issue by gamerscircle** [BobPalmer/SrvPack#57]
Using the version of Firespitter that comes with the SrvPack [7.1.5 according to KSP Add-on Version Checker] I have the "deploy option" available in the VAB and can use the "Gear" action group ouside the VAB.

With Firespitter 7.2, the deploy option is not available in the VAB and the action group doesn't work outside the VAB.

If this is not the correct process or I should report this on the other mod, point me in the correct direction.

**Comment by BobPalmer** [comment]
Deploy works fine in my latest test, it was never wired to the gear action.
