### ISSUE TITLE
Derp Pod missing Ablator Resource?

### ISSUE THREAD

**Issue by deimos790** [BobPalmer/SrvPack#58]
Copied from my forum post:

> And lastly, I noticed you gave the DERP Pod a "ModuleAblator" (ablativeResource = Ablator), but never actually gave it the Resouce Ablator. I thought maybe you added it in a MM patch, but couldn't find any. You do have a DRE patch, and looking in there I see you giving "ModuleHeatShield" and Resource AblativeShielding to a certain "USI_PodCapsule" (specifically FOR[SrvPack]). The only pod in the SrvPack, the DERP Pod, is part name "DERP_POD."

**Comment by BobPalmer** [comment]
Updated for next release
