### ISSUE TITLE
DERP POD spams logs in the VAB Editor

### ISSUE THREAD

**Issue by tarheel1999** [BobPalmer/SrvPack#66]
When the DERP_POD is selected in the VAB editor it spams the ouputlog with the following error:

> [AB] Error in OnFixedUpdate - Object reference not set to an instance of an object

This seems to be from this portion of LifeBoat.cs:

```
public void FixedUpdate()
        {
            try
            {
                if (part.checkLanded())
                {
                    Dampen();
                }
                if (part.Landed)
                {
                    Dampen();
                }
            }
            catch (Exception ex)
            {
                print("[AB] Error in OnFixedUpdate - " + ex.Message);
            }
        }
```

There are no errors when launched.  I've had the game crash several times when working with DERP pods in the editor especially working with several of them (I want to add them as escape pods to my space station).

**Comment by BobPalmer** [comment]
Fixed in next release
